apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oyfvjax3w-python 
  janus-idp.io/tekton: oyfvjax3w-python
  backstage.io/kubernetes-id: oyfvjax3w-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oyfvjax3w-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml